openapi: 3.0.0
info:
  title: StudentSync API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Placeholder endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
